// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcD8i9NbFN1jAkhzqXbmBkywtvzF7e4fI',
    appId: '1:828642726022:web:58e85b77dda529c75e0107',
    messagingSenderId: '828642726022',
    projectId: 'firestore-5d991',
    authDomain: 'firestore-5d991.firebaseapp.com',
    storageBucket: 'firestore-5d991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdCRFlMLodtIO3szUz7UF7n2gq1a76l0',
    appId: '1:828642726022:android:a82002edae341ba85e0107',
    messagingSenderId: '828642726022',
    projectId: 'firestore-5d991',
    storageBucket: 'firestore-5d991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL73Tx4SOkPRH0O6pbI9nNa-KsIHl07iQ',
    appId: '1:828642726022:ios:41a8487367f7463d5e0107',
    messagingSenderId: '828642726022',
    projectId: 'firestore-5d991',
    storageBucket: 'firestore-5d991.appspot.com',
    iosBundleId: 'com.example.todolistFirabases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL73Tx4SOkPRH0O6pbI9nNa-KsIHl07iQ',
    appId: '1:828642726022:ios:41a8487367f7463d5e0107',
    messagingSenderId: '828642726022',
    projectId: 'firestore-5d991',
    storageBucket: 'firestore-5d991.appspot.com',
    iosBundleId: 'com.example.todolistFirabases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcD8i9NbFN1jAkhzqXbmBkywtvzF7e4fI',
    appId: '1:828642726022:web:3478b44be5ce25c55e0107',
    messagingSenderId: '828642726022',
    projectId: 'firestore-5d991',
    authDomain: 'firestore-5d991.firebaseapp.com',
    storageBucket: 'firestore-5d991.appspot.com',
  );

}